name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get current date
      run: |
        echo "NOW=$(date '+%Y-%m-%dT%H_%M_%SZ')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag manchineel/mariadb_drive_dump:${NOW} --tag manchineel/mariadb_drive_dump:latest
    - name: Push to Docker Hub registry
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        docker push ${DOCKER_USER}/mariadb_drive_dump --all-tags
